openapi: 3.0.0
info:
  title: "REST API Demo"
  version: 1.0.0
servers:
  - url: http://localhost:9090/v1
paths:
  /healthcheck:
      get:
        tags:
            - Healthcheck
        summary: Health Check
        description: Retrieve information regarding service health
        responses:
          '200':
              description: OK
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      status:
                        type: string
                  example:
                      status: Success
